In [1]:
import numpy as np
import pandas as pd

file = r"CMU/CMU/01/01_01_poses.npz"
data = np.load(file, allow_pickle=True)

i = 0  # frame index
frame_pose = data["poses"][i]
frame_trans = data["trans"][i]
betas = data["betas"]

# Create a table for joint rotations
joint_indices = [f"Joint {j+1}" for j in range(len(frame_pose)//3)]
rotations = [frame_pose[j*3:(j+1)*3] for j in range(len(frame_pose)//3)]

df_poses = pd.DataFrame(rotations, index=joint_indices, columns=["Rx", "Ry", "Rz"])

# Root translation row
df_trans = pd.DataFrame([frame_trans], index=["Root Translation"], columns=["X", "Y", "Z"])

# Betas row
beta_indices = [f"Beta {j+1}" for j in range(len(betas))]
df_betas = pd.DataFrame([betas], columns=beta_indices)

# Display nicely
print("Joint Rotations (Axis–Angle) for Frame", i)
display(df_poses.round(3))
print("\nRoot Joint Translation")
display(df_trans.round(3))
print("\nBody Shape Parameters (Betas)")
display(df_betas.round(3))

Joint Rotations (Axis–Angle) for Frame 0

             Rx     Ry     Rz
Joint 1   1.197  1.106  1.205
Joint 2   0.096 -0.048  0.032
Joint 3  -0.000 -0.002 -0.022
Joint 4   0.039 -0.046 -0.018
Joint 5   0.160 -0.079 -0.055
Joint 6   0.347  0.014 -0.014
Joint 7   0.014 -0.036  0.035
Joint 8  -0.299  0.225  0.043
Joint 9  -0.347 -0.078  0.068
Joint 10  0.024 -0.016 -0.023
Joint 11  0.000  0.000  0.000
Joint 12  0.000  0.000  0.000
Joint 13 -0.064  0.156 -0.045
Joint 14 -0.149 -0.081 -0.219
Joint 15 -0.001  0.042  0.420
Joint 16  0.511 -0.006  0.010
Joint 17 -0.051 -0.865 -0.528
Joint 18  0.214  0.273  1.076
Joint 19 -0.018 -2.076  0.724
Joint 20 -0.165  0.274 -0.140
Joint 21 -0.497 -0.416  0.413
Joint 22 -0.386  0.146 -0.031
Joint 23  0.112  0.043 -0.416
Joint 24  0.109 -0.066 -0.756
Joint 25 -0.096 -0.091 -0.188
Joint 26 -0.118  0.051 -0.530
Joint 27 -0.144  0.055 -0.705
Joint 28 -0.019 -0.092 -0.338
Joint 29 -0.457 -0.196 -0.625
Joint 30 -0.215 -0.066 -0.507
Joint 31 -0.370 -0.060 -0.079
Joint 32 -0.142 -0.086 -0.636
Joint 33 -0.303 -0.058 -0.631
Joint 34 -0.176 -0.132 -0.373
Joint 35  0.851  0.277 -0.092
Joint 36 -0.500  0.027  0.053
Joint 37  0.536  0.046 -0.277
Joint 38  0.112 -0.043  0.416
Joint 39  0.109  0.066  0.756
Joint 40 -0.096  0.091  0.188
Joint 41 -0.118 -0.051  0.530
Joint 42 -0.144 -0.055  0.705
Joint 43 -0.019  0.092  0.338
Joint 44 -0.457  0.196  0.625
Joint 45 -0.215  0.066  0.507
Joint 46 -0.370  0.060  0.079
Joint 47 -0.142  0.086  0.636
Joint 48 -0.303  0.058  0.631
Joint 49 -0.176  0.132  0.373
Joint 50  0.851 -0.277  0.092
Joint 51 -0.500 -0.027 -0.053
Joint 52  0.536 -0.046  0.277

Root Joint Translation

                     X      Y      Z
Root Translation -0.94  0.766  0.961

Body Shape Parameters (Betas)

,Beta 1,Beta 2,Beta 3,Beta 4,Beta 5,Beta 6,Beta 7,Beta 8,Beta 9,Beta 10,Beta 11,Beta 12,Beta 13,Beta 14,Beta 15,Beta 16
0,-0.263,1.471,-0.317,0.323,0.695,0.07,1.155,-2.035,1.255,-0.963,-0.623,0.733,0.54,0.634,-0.254,0.576

In [4]:
import numpy as np
import pandas as pd

# Load a sample frame
file = r"CMU/CMU/01/01_01_poses.npz"
data = np.load(file, allow_pickle=True)

i = 0  # frame index
frame_pose = data["poses"][i]
frame_trans = data["trans"][i]
betas = data["betas"]

# ===================== 1️⃣ Joint Rotations =====================
num_joints = len(frame_pose) // 3
joint_names = [f"Joint {j+1}" for j in range(num_joints)]
rotation_columns = ["Rx", "Ry", "Rz"]
rotations = [frame_pose[j*3:(j+1)*3] for j in range(num_joints)]

df_poses = pd.DataFrame(rotations, index=joint_names, columns=rotation_columns)

# Add multi-level header
df_poses.columns = pd.MultiIndex.from_product([["Joint Rotations"], rotation_columns])

# ===================== 2️⃣ Root Translation =====================
df_trans = pd.DataFrame([frame_trans], index=["Root Translation"], columns=["X", "Y", "Z"])
df_trans.columns = pd.MultiIndex.from_product([["Root Translation (m)"], df_trans.columns])

# ===================== 3️⃣ Body Shape (Betas) =====================
beta_names = [f"Beta {j+1}" for j in range(len(betas))]
df_betas = pd.DataFrame([betas], index=["Betas"])
df_betas.columns = pd.MultiIndex.from_product([["Body Shape Parameters"], df_betas.columns])

# ===================== Display =====================
print(f"Frame {i} - Joint Rotations, Translation, Betas")
display(df_poses.round(3))
display(df_trans.round(3))
display(df_betas.round(3))

Frame 0 - Joint Rotations, Translation, Betas

         Joint Rotations
                      Rx     Ry     Rz
Joint 1            1.197  1.106  1.205
Joint 2            0.096 -0.048  0.032
Joint 3           -0.000 -0.002 -0.022
Joint 4            0.039 -0.046 -0.018
Joint 5            0.160 -0.079 -0.055
Joint 6            0.347  0.014 -0.014
Joint 7            0.014 -0.036  0.035
Joint 8           -0.299  0.225  0.043
Joint 9           -0.347 -0.078  0.068
Joint 10           0.024 -0.016 -0.023
Joint 11           0.000  0.000  0.000
Joint 12           0.000  0.000  0.000
Joint 13          -0.064  0.156 -0.045
Joint 14          -0.149 -0.081 -0.219
Joint 15          -0.001  0.042  0.420
Joint 16           0.511 -0.006  0.010
Joint 17          -0.051 -0.865 -0.528
Joint 18           0.214  0.273  1.076
Joint 19          -0.018 -2.076  0.724
Joint 20          -0.165  0.274 -0.140
Joint 21          -0.497 -0.416  0.413
Joint 22          -0.386  0.146 -0.031
Joint 23           0.112  0.043 -0.416
Joint 24           0.109 -0.066 -0.756
Joint 25          -0.096 -0.091 -0.188
Joint 26          -0.118  0.051 -0.530
Joint 27          -0.144  0.055 -0.705
Joint 28          -0.019 -0.092 -0.338
Joint 29          -0.457 -0.196 -0.625
Joint 30          -0.215 -0.066 -0.507
Joint 31          -0.370 -0.060 -0.079
Joint 32          -0.142 -0.086 -0.636
Joint 33          -0.303 -0.058 -0.631
Joint 34          -0.176 -0.132 -0.373
Joint 35           0.851  0.277 -0.092
Joint 36          -0.500  0.027  0.053
Joint 37           0.536  0.046 -0.277
Joint 38           0.112 -0.043  0.416
Joint 39           0.109  0.066  0.756
Joint 40          -0.096  0.091  0.188
Joint 41          -0.118 -0.051  0.530
Joint 42          -0.144 -0.055  0.705
Joint 43          -0.019  0.092  0.338
Joint 44          -0.457  0.196  0.625
Joint 45          -0.215  0.066  0.507
Joint 46          -0.370  0.060  0.079
Joint 47          -0.142  0.086  0.636
Joint 48          -0.303  0.058  0.631
Joint 49          -0.176  0.132  0.373
Joint 50           0.851 -0.277  0.092
Joint 51          -0.500 -0.027 -0.053
Joint 52           0.536 -0.046  0.277

                 Root Translation (m)
                                    X      Y      Z
Root Translation                -0.94  0.766  0.961

      Body Shape Parameters                                                  \
                         0      1      2      3      4     5      6      7
Betas                -0.263  1.471 -0.317  0.323  0.695  0.07  1.155 -2.035


          8      9      10     11    12     13     14     15
Betas  1.255 -0.963 -0.623  0.733  0.54  0.634 -0.254  0.576